libmysqlclient.so.18: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 662, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 25, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 50, in get_partner_stats
    for provider in self.get_providers():
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 102, in get_providers
    return Provider.query.all()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2829, in __call__
    return self.class_(**local_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 145, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in engine
    return self.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 543, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
libmysqlclient.so.18: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 662, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 25, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 50, in get_partner_stats
    for provider in self.get_providers():
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 102, in get_providers
    return Provider.query.all()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2829, in __call__
    return self.class_(**local_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 145, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in engine
    return self.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 543, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
unsupported operand type(s) for +: 'Markup' and 'int'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 323, in top-level template code
    <span>{{ _('Um projecto de') + (3+6) }}:</span>
TypeError: unsupported operand type(s) for +: 'Markup' and 'int'
']]>' not allowed inside CDATA
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 282, in get_kml_for_fields
    et.SubElement(placemark, "description").text = CDATA(_content)
  File "src/lxml/lxml.etree.pyx", line 3075, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:77521)
ValueError: ']]>' not allowed inside CDATA
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection).encode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 274, in get_kml_for_fields
    's')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
'OrderedDict' object is not callable
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 274, in get_kml_for_fields
    collection.as_dict(),
TypeError: 'OrderedDict' object is not callable
All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 279, in get_kml_for_fields
    et.SubElement(placemark, "description").text = CDATA(_content)
  File "src/lxml/lxml.etree.pyx", line 3073, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:77494)
  File "src/lxml/apihelpers.pxi", line 1443, in lxml.etree._utf8 (src/lxml/lxml.etree.c:31502)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 279, in get_kml_for_fields
    et.SubElement(placemark, "description").text = CDATA(_content)
  File "src/lxml/lxml.etree.pyx", line 3073, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:77494)
  File "src/lxml/apihelpers.pxi", line 1443, in lxml.etree._utf8 (src/lxml/lxml.etree.c:31502)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 274, in get_kml_for_fields
    unidecode(collection.get_header('header.taxonomy').encode('utf-8')),
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/unidecode/__init__.py", line 48, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
write() got an unexpected keyword argument 'remove_blank_text'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 282, in get_kml_for_fields
    tree.write(output, pretty_print=False, xml_declaration=True, encoding='utf-8', remove_blank_text=True)
  File "src/lxml/lxml.etree.pyx", line 1955, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:64491)
TypeError: write() got an unexpected keyword argument 'remove_blank_text'
write() got an unexpected keyword argument 'indent'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 282, in get_kml_for_fields
    tree.write(output, pretty_print=False, xml_declaration=True, encoding='utf-8', indent='', newl='')
  File "src/lxml/lxml.etree.pyx", line 1955, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:64491)
TypeError: write() got an unexpected keyword argument 'indent'
write() got an unexpected keyword argument 'indent'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 282, in get_kml_for_fields
    tree.write(output, pretty_print=False, xml_declaration=True, encoding='utf-8', indent='', newl='')
  File "src/lxml/lxml.etree.pyx", line 1955, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:64491)
TypeError: write() got an unexpected keyword argument 'indent'
'_io.BytesIO' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 428, in download_kml
    _format = _kml_content[1]
TypeError: '_io.BytesIO' object has no attribute '__getitem__'
'_io.BytesIO' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 428, in download_kml
    _format = _kml_content[1]
TypeError: '_io.BytesIO' object has no attribute '__getitem__'
(_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'a7e4sgso2kxq2hsi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com' (-2)")
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 664, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 52, in get_partner_stats
    for provider in self.get_providers():
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 104, in get_providers
    return Provider.query.all()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
    close_with_result=True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
    **kw
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 966, in connection
    execution_options=execution_options)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (_mysql_exceptions.OperationalError) (2005, "Unknown MySQL server host 'a7e4sgso2kxq2hsi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com' (-2)")
a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 659, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 54, in get_partner_stats
    if provider.logo is not None:
  File "/usr/lib/python3.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 35, in logo
    return multimedia_to_image(multimedia)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 32, in multimedia_to_image
    _encoded_multimedia_id = encode_text(str(multimedia.id)) if multimedia is not None else encode_text('-1')
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 24, in encode_text
    return base64.b64encode(text)
  File "/usr/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
sequence item 1: expected str instance, bytes found
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 659, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 54, in get_partner_stats
    if provider.logo is not None:
  File "/usr/lib/python3.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 35, in logo
    return multimedia_to_image(multimedia)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 37, in multimedia_to_image
    _encoded_multimedia_type])
TypeError: sequence item 1: expected str instance, bytes found
No module named 'MySQLdb'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 988, in __call__
    return self.registry[key]
KeyError: 140521639589632

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 659, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 52, in get_partner_stats
    for provider in self.get_providers():
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 104, in get_providers
    return Provider.query.all()
  File "/usr/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2829, in __call__
    return self.class_(**local_kw)
  File "/usr/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 145, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/usr/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in engine
    return self.get_engine()
  File "/usr/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/usr/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 543, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
ModuleNotFoundError: No module named 'MySQLdb'
a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 659, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 54, in get_partner_stats
    if provider.logo is not None:
  File "/usr/lib/python3.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 35, in logo
    return multimedia_to_image(multimedia)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 32, in multimedia_to_image
    _encoded_multimedia_id = encode_text(str(multimedia.id)) if multimedia is not None else encode_text('-1')
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 24, in encode_text
    return base64.b64encode(text)
  File "/usr/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 659, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 27, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 54, in get_partner_stats
    if provider.logo is not None:
  File "/usr/lib/python3.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 35, in logo
    return multimedia_to_image(multimedia)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 32, in multimedia_to_image
    _encoded_multimedia_id = encode_text(str(multimedia.id)) if multimedia is not None else encode_text('-1')
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/helper.py", line 24, in encode_text
    return base64.b64encode(text).decode('utf-8')
  File "/usr/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
name 'basestring' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 159, in top-level template code
    {{ forms['advanced'][_form_names.name_province](
  File "/usr/lib/python3.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/lib/python3.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/lib/python3.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    func_result = unicode(value) if isinstance(value, basestring) else coerce_func(value)
NameError: name 'basestring' is not defined
name 'unicode' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 43, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python3.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 159, in top-level template code
    {{ forms['advanced'][_form_names.name_province](
  File "/usr/lib/python3.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/lib/python3.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/lib/python3.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 141, in render_option
    func_result = unicode(value) if isinstance(value, string_types) else coerce_func(value)
NameError: name 'unicode' is not defined
