libmysqlclient.so.18: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 662, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 25, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 50, in get_partner_stats
    for provider in self.get_providers():
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 102, in get_providers
    return Provider.query.all()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2829, in __call__
    return self.class_(**local_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 145, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in engine
    return self.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 543, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
libmysqlclient.so.18: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 662, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 25, in get_portal_data
    providers = self.get_partner_stats()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 50, in get_partner_stats
    for provider in self.get_providers():
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 102, in get_providers
    return Provider.query.all()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2829, in __call__
    return self.class_(**local_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 145, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 922, in engine
    return self.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 941, in get_engine
    return connector.get_engine()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 543, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 110, in dbapi
    return __import__('MySQLdb')
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
unsupported operand type(s) for +: 'Markup' and 'int'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 323, in top-level template code
    <span>{{ _('Um projecto de') + (3+6) }}:</span>
TypeError: unsupported operand type(s) for +: 'Markup' and 'int'
']]>' not allowed inside CDATA
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 282, in get_kml_for_fields
    et.SubElement(placemark, "description").text = CDATA(_content)
  File "src/lxml/lxml.etree.pyx", line 3075, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:77521)
ValueError: ']]>' not allowed inside CDATA
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection).encode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 274, in get_kml_for_fields
    's')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 275, in get_kml_for_fields
    self.get_taxonomical_tree_as_str_html(collection))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)
'OrderedDict' object is not callable
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 274, in get_kml_for_fields
    collection.as_dict(),
TypeError: 'OrderedDict' object is not callable
All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 279, in get_kml_for_fields
    et.SubElement(placemark, "description").text = CDATA(_content)
  File "src/lxml/lxml.etree.pyx", line 3073, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:77494)
  File "src/lxml/apihelpers.pxi", line 1443, in lxml.etree._utf8 (src/lxml/lxml.etree.c:31502)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 279, in get_kml_for_fields
    et.SubElement(placemark, "description").text = CDATA(_content)
  File "src/lxml/lxml.etree.pyx", line 3073, in lxml.etree.CDATA.__cinit__ (src/lxml/lxml.etree.c:77494)
  File "src/lxml/apihelpers.pxi", line 1443, in lxml.etree._utf8 (src/lxml/lxml.etree.c:31502)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 426, in download_kml
    _csv_content = service.get_kml_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 274, in get_kml_for_fields
    unidecode(collection.get_header('header.taxonomy').encode('utf-8')),
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/unidecode/__init__.py", line 48, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
